# Machine Learning Engineer Nanodegree
## Capstone Proposal
Dmytro Iakubovskyi 
September 30th, 2017

## Proposal
_(approx. 2-3 pages)_

**Major question to answer**:
- What types of usage patterns exist during studentsâ€™ interaction with intelligent tutoring systems, and what usage patterns correlate with ultimate successful learning? (Answerable with the Assistments dataset from PSLC DataShop)

*** DI: THE END OF MY CHANGES ***

### Domain Background
_(approx. 1-2 paragraphs)_

In this section, provide brief details on the background information of the domain from which the project is proposed. Historical information relevant to the project should be included. It should be clear how or why a problem in the domain can or should be solved. Related academic research should be appropriately cited in this section, including why that research is relevant. Additionally, a discussion of your personal motivation for investigating a particular problem in the domain is encouraged but not required.

### Problem Statement
_(approx. 1 paragraph)_

In this section, clearly describe the problem that is to be solved. The problem described should be well defined and should have at least one relevant potential solution. Additionally, describe the problem thoroughly such that it is clear that the problem is quantifiable (the problem can be expressed in mathematical or logical terms) , measurable (the problem can be measured by some metric and clearly observed), and replicable (the problem can be reproduced and occurs more than once).

### Datasets and Inputs
_(approx. 2-3 paragraphs)_

In this section, the dataset(s) and/or input(s) being considered for the project should be thoroughly described, such as how they relate to the problem and why they should be used. Information such as how the dataset or input is (was) obtained, and the characteristics of the dataset or input, should be included with relevant references and citations as necessary It should be clear how the dataset(s) or input(s) will be used in the project and whether their use is appropriate given the context of the problem.

### Solution Statement
_(approx. 1 paragraph)_

In this section, clearly describe a solution to the problem. The solution should be applicable to the project domain and appropriate for the dataset(s) or input(s) given. Additionally, describe the solution thoroughly such that it is clear that the solution is quantifiable (the solution can be expressed in mathematical or logical terms) , measurable (the solution can be measured by some metric and clearly observed), and replicable (the solution can be reproduced and occurs more than once).

### Benchmark Model
_(approximately 1-2 paragraphs)_

In this section, provide the details for a benchmark model or result that relates to the domain, problem statement, and intended solution. Ideally, the benchmark model or result contextualizes existing methods or known information in the domain and problem given, which could then be objectively compared to the solution. Describe how the benchmark model or result is measurable (can be measured by some metric and clearly observed) with thorough detail.

### Evaluation Metrics
_(approx. 1-2 paragraphs)_

In this section, propose at least one evaluation metric that can be used to quantify the performance of both the benchmark model and the solution model. The evaluation metric(s) you propose should be appropriate given the context of the data, the problem statement, and the intended solution. Describe how the evaluation metric(s) are derived and provide an example of their mathematical representations (if applicable). Complex evaluation metrics should be clearly defined and quantifiable (can be expressed in mathematical or logical terms).

### Project Design
_(approx. 1 page)_

In this final section, summarize a theoretical workflow for approaching a solution given the problem. Provide thorough discussion for what strategies you may consider employing, what analysis of the data might be required before being used, or which algorithms will be considered for your implementation. The workflow and discussion that you provide should align with the qualities of the previous sections. Additionally, you are encouraged to include small visualizations, pseudocode, or diagrams to aid in describing the project design, but it is not required. The discussion should clearly outline your intended workflow of the capstone project.

-----------

**Before submitting your proposal, ask yourself. . .**

- Does the proposal you have written follow a well-organized structure similar to that of the project template?
- Is each section (particularly **Solution Statement** and **Project Design**) written in a clear, concise and specific fashion? Are there any ambiguous terms or phrases that need clarification?
- Would the intended audience of your project be able to understand your proposal?
- Have you properly proofread your proposal to assure there are minimal grammatical and spelling mistakes?
- Are all the resources used for this project correctly cited and referenced?

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
mcas_scores = pd.read_csv("wpi-assistments/math_2004_2005/mcas_scores_0405.csv")

In [3]:
mcas_scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 2 columns):
datashop_anon_id    683 non-null object
mcas_score          683 non-null int64
dtypes: int64(1), object(1)
memory usage: 10.8+ KB

In [4]:
mcas_scores.head()

                       datashop_anon_id  mcas_score
0  Stu_42a0e188f5033bc65bf8d78622277c4e          34
1  Stu_3988c7f88ebcb58c6ce932b957b6f332          39
2  Stu_e00da03b685a0dd18fb6a08af0923de0          37
3  Stu_1385974ed5904a438616ff7bdb3f7439          35
4  Stu_0f28b5d49b3020afeecd95b4009adf4c          46

In [5]:
mcas_scores.describe()

       mcas_score
count  683.000000
mean    25.171303
std     12.206133
min      0.000000
25%     15.000000
50%     23.000000
75%     35.000000
max     53.000000

In [6]:
dataframe2 = pd.read_csv("wpi-assistments/math_2004_2005/dataframe2_WPI-Apr-2005.txt", sep="\t")
dataframe2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2568 entries, 0 to 2567
Columns: 109 entries, ID to long division
dtypes: int64(107), object(2)
memory usage: 2.1+ MB

In [7]:
dataframe2.head()

,ID,ProblemFile,QuestionFile,360-Degrees-in-Circle,Adding-Decimals,Addition,Algebraic-Manipulation,Area,Area-Concept,Area-of-Circle,...,Symbolization-Articulation,Transformations/Rotations,Transversals,Triangle-Inequality,Understanding_Line_Slope_Intercept,Unit-Conversion,Venn-Diagram,Volume,X-Y-Graph,long division
0,7,/MA/Item 18 G-2001 (Points on translated image...,/MA/Item 18 G-2001 (Points on translated image...,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,8,/MA/Item 18 G-2001 (Points on translated image...,/MA/Item 18 G-2001 (Points on translated image...,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,9,/MA/Item 18 G-2001 (Points on translated image...,/MA/Item 18 G-2001 (Points on translated image...,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,10,/MA/Item 18 G-2001 (Points on translated image...,/MA/Item 18 G-2001 (Points on translated image...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,11,/MA/Item 18 G-2001 (Points on translated image...,/MA/Item 18 G-2001 (Points on translated image...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
dataframe3 = pd.read_csv("wpi-assistments/math_2004_2005/dataframe3_aggr.txt.output.txt", sep="\t")
dataframe3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226099 entries, 0 to 226098
Data columns (total 12 columns):
studentID                226099 non-null int64
itemid                   226099 non-null int64
correctonfirstattempt    226099 non-null int64
attempts                 226099 non-null int64
hints                    226099 non-null int64
seconds                  226099 non-null int64
full_start_time          226099 non-null object
full_finish_time         226099 non-null object
start_day                226099 non-null object
start_time               226099 non-null object
finish_day               226099 non-null object
finish_time              226099 non-null object
dtypes: int64(6), object(6)
memory usage: 20.7+ MB

In [9]:
dataframe3.head()

,studentID,itemid,correctonfirstattempt,attempts,hints,seconds,full_start_time,full_finish_time,start_day,start_time,finish_day,finish_time
0,136,90,1,1,0,58,01-OCT-04 07.44.43.000000 AM,01-OCT-04 07.45.41.000000 AM,01-OCT-04,7.44.43,01-OCT-04,7.45.41
1,136,91,0,1,3,91,10-DEC-04 09.27.20.000000 AM,10-DEC-04 09.28.51.000000 AM,10-DEC-04,9.27.20,10-DEC-04,9.28.51
2,136,92,1,1,0,11,10-DEC-04 09.28.51.000000 AM,10-DEC-04 09.29.02.000000 AM,10-DEC-04,9.28.51,10-DEC-04,9.29.2
3,136,93,1,1,0,10,10-DEC-04 09.29.02.000000 AM,10-DEC-04 09.29.12.000000 AM,10-DEC-04,9.29.2,10-DEC-04,9.29.12
4,136,94,0,2,0,43,10-DEC-04 09.29.12.000000 AM,10-DEC-04 09.29.55.000000 AM,10-DEC-04,9.29.12,10-DEC-04,9.29.55

In [10]:
len(set(dataframe3['studentID']))

912

In [11]:
len(set(dataframe3['itemid']))

1709

In [12]:
ds92_tx_Data1 = pd.read_csv('wpi-assistments/math_2004_2005/ds92_tx_Data1_914_2016_0504_082925.txt', \
                            sep="\t", \
                            low_memory=False)

In [13]:
ds92_tx_Data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 580785 entries, 0 to 580784
Data columns (total 66 columns):
Row                                        580785 non-null int64
Sample Name                                580785 non-null object
Transaction Id                             580785 non-null object
Anon Student Id                            580785 non-null object
Session Id                                 580785 non-null int64
Time                                       580785 non-null object
Time Zone                                  580785 non-null object
Duration (sec)                             580785 non-null object
Student Response Type                      580785 non-null object
Student Response Subtype                   0 non-null float64
Tutor Response Type                        580327 non-null object
Tutor Response Subtype                     0 non-null float64
Level (Curriculum)                         580785 non-null object
Problem Name                               580785 non-null int64
Problem View                               579989 non-null float64
Problem Start Time                         579989 non-null object
Step Name                                  580327 non-null object
Attempt At Step                            580327 non-null float64
Is Last Attempt                            580327 non-null float64
Outcome                                    580327 non-null object
Selection                                  580785 non-null object
Action                                     0 non-null float64
Input                                      362197 non-null object
Feedback Text                              325502 non-null object
Feedback Classification                    210626 non-null object
Help Level                                 210626 non-null float64
Total Num Hints                            0 non-null float64
KC (skills_from_dataframe)                 531575 non-null object
KC Category (skills_from_dataframe)        0 non-null float64
KC (skills_from_dataframe).1               50731 non-null object
KC Category (skills_from_dataframe).1      0 non-null float64
KC (skills_from_dataframe).2               8474 non-null object
KC Category (skills_from_dataframe).2      0 non-null float64
KC (skills_from_dataframe).3               1125 non-null object
KC Category (skills_from_dataframe).3      0 non-null float64
KC (WPI-Apr-2005)                          535334 non-null object
KC Category (WPI-Apr-2005)                 0 non-null float64
KC (WPI-Apr-2005).1                        54546 non-null object
KC Category (WPI-Apr-2005).1               0 non-null float64
KC (WPI-Apr-2005).2                        9150 non-null object
KC Category (WPI-Apr-2005).2               0 non-null float64
KC (WPI-Apr-2005).3                        1125 non-null object
KC Category (WPI-Apr-2005).3               0 non-null float64
KC (MCAS39-State_WPI-Simple)               314673 non-null object
KC Category (MCAS39-State_WPI-Simple)      0 non-null float64
KC (MCAS39-State_WPI-Simple).1             71165 non-null object
KC Category (MCAS39-State_WPI-Simple).1    0 non-null float64
KC (MCAS39-State_WPI-Simple).2             17485 non-null object
KC Category (MCAS39-State_WPI-Simple).2    0 non-null float64
KC (MCAS39-State_WPI-Simple).3             1223 non-null object
KC Category (MCAS39-State_WPI-Simple).3    0 non-null float64
KC (MCAS5-State_WPI-Simple)                468727 non-null object
KC Category (MCAS5-State_WPI-Simple)       0 non-null float64
KC (MCAS5-State_WPI-Simple).1              9747 non-null object
KC Category (MCAS5-State_WPI-Simple).1     0 non-null float64
KC (MCAS5-State_WPI-Simple).2              8 non-null object
KC Category (MCAS5-State_WPI-Simple).2     0 non-null float64
KC (MCAS5-State_WPI-Simple).3              8 non-null object
KC Category (MCAS5-State_WPI-Simple).3     0 non-null float64
KC (Single-KC)                             580327 non-null object
KC Category (Single-KC)                    0 non-null float64
KC (Unique-step)                           513275 non-null object
KC Category (Unique-step)                  0 non-null float64
School                                     580785 non-null object
Class                                      580785 non-null object
CF (mich)                                  0 non-null float64
dtypes: float64(27), int64(3), object(36)
memory usage: 292.4+ MB

In [14]:
ds92_tx_Data1.head()

,Row,Sample Name,Transaction Id,Anon Student Id,Session Id,Time,Time Zone,Duration (sec),Student Response Type,Student Response Subtype,...,KC Category (MCAS5-State_WPI-Simple).2,KC (MCAS5-State_WPI-Simple).3,KC Category (MCAS5-State_WPI-Simple).3,KC (Single-KC),KC Category (Single-KC),KC (Unique-step),KC Category (Unique-step),School,Class,CF (mich)
0,1,Data1,f4e16b8c0864cb38ffbd487d846a09e1,Stu_001d187b1b375fe98b88696b250177f0,647501,2004-11-10 14:36:52,US/Eastern,102,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC758,NaN,0103999,Class_2,NaN
1,2,Data1,e44529ccdaa26422c653ff9c1efec8c6,Stu_001d187b1b375fe98b88696b250177f0,647501,2004-11-10 14:37:38,US/Eastern,46,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC758,NaN,0103999,Class_2,NaN
2,3,Data1,9915b5078ecd2b8fa0b6f246a021db4b,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:38:50,US/Eastern,70,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC790,NaN,0103999,Class_2,NaN
3,4,Data1,7e36958c6d8d08d9b15ff7f133a76da0,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:39:12,US/Eastern,22,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
4,5,Data1,8f1aef4b136c9ed4ce89c75d9a7dda7c,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:39:14,US/Eastern,2,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN

In [15]:
ds92_tx_Data1['Anon Student Id'] = ds92_tx_Data1['Anon Student Id'].astype(str)

In [16]:
len(set(ds92_tx_Data1['Anon Student Id']))

912

In [17]:
set(ds92_tx_Data1['Anon Student Id'])

{'Stu_001d187b1b375fe98b88696b250177f0',
 'Stu_00b8a37b3ab49bfe7d7a77014d1e4cf8',
 'Stu_00c6652f296f103913139157c79a856f',
 'Stu_01080cce4b1a14b3fd81d684421daed4',
 'Stu_0153c9b08d68e42d9a2bb5f70086df00',
 'Stu_01b10767cda9a06c1a58a4f65ba3510d',
 'Stu_01cb10d2dbc94d8a69423db3cf238cac',
 'Stu_01d27e10411da46a9337d9f5610e8216',
 'Stu_01f585b308698102e506f1e7c23386cd',
 'Stu_020e782c7d872460f71e905692b1f5ba',
 'Stu_0239ccd30694a9860cbc74333f515b0a',
 'Stu_0256e28026417b04c8b5bc4da00f1966',
 'Stu_02ddafacabbcfe2c156c1e79d381c104',
 'Stu_02de555a465f53df4074daa4c5aa34a5',
 'Stu_0311b4e015e05d6edf932ec468cb6a65',
 'Stu_03530655aaf51d45475d9a09f8a3d177',
 'Stu_03b8857b2a4d30255ec31d81acc6c89c',
 'Stu_0444a864e86402654e8038b57149f2a5',
 'Stu_0469d25a656b200037acd31fa174b5c8',
 'Stu_0487de336fcfc6c21d7f3249dd153c85',
 'Stu_0512277a8b0a10cda6ce68e7d2900d84',
 'Stu_0521933ce1398481399524722dd2bd5e',
 'Stu_055d2ebee188c575cfe8d9472432fab8',
 'Stu_056e4235208e3a332e876428bcc84dda',
 'Stu_05a3fda2e596133d7f423e9167943f3b',
 'Stu_05da4e2efb3b225fcbf1eae93591f1c7',
 'Stu_062022167bc35f1c0fb39fa96cb37803',
 'Stu_06e30f7fc5ed1e8feb556c069b61ddd7',
 'Stu_06f2d6148eaa02396e28c9607aca901e',
 'Stu_0797fc86f4685c3546754af3bc7cbcff',
 'Stu_07eb7d4948ab61911ea1ddac5226b385',
 'Stu_082824a169ac621702e4548febe0351f',
 'Stu_08489ddea5af30ba6985433029a56abb',
 'Stu_089bf1c5a3486f030042af34ef406856',
 'Stu_0918d12f67b4c2cd5491790f0c14124f',
 'Stu_0967c267acfa151599ab9911d6cc98a0',
 'Stu_09bac1944f932e0db4956657ccf36b82',
 'Stu_09e697a1f5646bd14ef37cfcbb806a63',
 'Stu_0aeb88a42afd8b15dc889226af0319f2',
 'Stu_0b4712205ce1bf208d27b672bc0af14b',
 'Stu_0b586f78e257bcba50be6353575cab81',
 'Stu_0b687016e804bf0fe2e39614e0c97e03',
 'Stu_0b9017bacaa3468a793e172a5d46367c',
 'Stu_0c77263c69d9e631e7d49b8cfc8e9461',
 'Stu_0c9a8df5d42bbb5420e86165bc5287d9',
 'Stu_0cb960389c74c5e7d1a79bfb19b2d952',
 'Stu_0d25b5386c3cb75c46520e68385f1f0d',
 'Stu_0e1086c6cbbde67829953d5757a03d3e',
 'Stu_0e3725341fd025221a612b2b0708d967',
 'Stu_0e5e97c806197f118829a6073f7b0357',
 'Stu_0e8bf4ff4db4637d4eaa0dfda8f04b8f',
 'Stu_0fa55c06a7b47d878236fd9908d4e0db',
 'Stu_0fd7264bec2575599fce140880ca9453',
 'Stu_0ff17602b72f92d9cb20f81fb18d3514',
 'Stu_1083d713a9f2624ee78149fb6f64ee19',
 'Stu_11378f9c3d72d009532bb76e7a6a64a2',
 'Stu_123ebdb2e135fe275dcce5a99d0d7f6f',
 'Stu_124c378caef064ec6fe350926d16589f',
 'Stu_12894f67fd9b36b09a87ec8796ea65dd',
 'Stu_13072ef6a2e4f0be1abce53fc49870a8',
 'Stu_134fb357ad11bf2c5f3547fb2c1d53e5',
 'Stu_13f1900bb10fea6e773ebd047ac8ac6b',
 'Stu_147be5b9e9d24811178259fabe92e085',
 'Stu_14cce5a18fbfe24699ec202b9e6fc754',
 'Stu_14de949c74d81fc2cb6b4e372e27015c',
 'Stu_14e6aaae88519072da8edc52c3f38fc2',
 'Stu_14e7e52b884b6139a387cfb6852369c7',
 'Stu_157783dc3c6a0a0d7e65049c244b2ac7',
 'Stu_15b93c7ad28be70b408c5ce88fa6f476',
 'Stu_15ce9c54d02599ec956b7d188c4001ac',
 'Stu_1669a3977c4e6f0c6a8d8f3d35d1e5e7',
 'Stu_16c4d4db29ce529fa32c5ca849d67421',
 'Stu_1764ea2da9858628ef966dd27f839fc0',
 'Stu_178e20fde4a271c70c5a9a5f4a2bb8bd',
 'Stu_17daa096aa37621557622224ae963736',
 'Stu_1815ee59311572a14b1eb9631d7dff48',
 'Stu_18349757cc3dabd8d1791119352fb366',
 'Stu_1834d42c090d8962a9f208ba4b6cbfe6',
 'Stu_18cc06a1902e91225c21331ca4eef105',
 'Stu_19227c7e55aec2a00f717ba9d8ee040d',
 'Stu_194159d8c3ccf9aa6ec482bd12060227',
 'Stu_19a4d58ad6a7bd56d9e3b44b1d351f15',
 'Stu_19b2995e22f8f3ccb2bf135d30d8a353',
 'Stu_1a4fd0118ee6e656a6ecbb0856eea10c',
 'Stu_1b134eef226e3b741fb4b0f3e71b71ea',
 'Stu_1b7b64e970209a612cfca5c4383cdb87',
 'Stu_1b821fedbfaf19717f2bad2a1430c822',
 'Stu_1c1c2208473384c6b48d0f927b872b9c',
 'Stu_1ca6452a9469db635a5ce4d9f2895372',
 'Stu_1cfe8aa80964062c17a62d4dd8d58331',
 'Stu_1d3b484918a3087685b09b87252639de',
 'Stu_1dcfbf44e56957cd4cfbe57814a4bb3b',
 'Stu_1ddaea9def1a7bf6ab4cb060117e9488',
 'Stu_1e3c568f5dc0fffdba02ee6e7c9bd31b',
 'Stu_1e44157597338f5aff9e174dc81d0301',
 'Stu_1e77c0e89f7e330188d64a23c7b1d607',
 'Stu_1ebffe3514eb4bd3036640c2044ad091',
 'Stu_1ec7dbcad56319aa7de4a9e2533b08d0',
 'Stu_1eccb16a0abc3943ac80f777c36ca739',
 'Stu_1ef86a9ac92d666bb2c99f64fb575ac2',
 'Stu_1f5a2198d1ffec4e17bdd679311b3dc2',
 'Stu_1f69e7962cd9dd71e1c0ba852a26f6ad',
 'Stu_1f7be932379133484a4fe00550dc89d5',
 'Stu_1f865743c30771ca9cbade94aef38909',
 'Stu_1fd7549028cd500f40b9b6f03c77a401',
 'Stu_20825f9007a1913a257e97047330c992',
 'Stu_20882f99969e62e3e3e14301beedcbe4',
 'Stu_20a265ca745da48ce3794a0bb9c53193',
 'Stu_20ab3b4778e53289eccb98712061e9a1',
 'Stu_20c1dd89c92312dcbfcba0fb3c1666de',
 'Stu_2123aeb53b95254a0a198507e13e8b01',
 'Stu_21516cdddd3f8537bdde48632f27e65c',
 'Stu_21c9d6dc8a5f8643a433271d481a7cf9',
 'Stu_2241de6049144b46a3ab3a9ff9f9f478',
 'Stu_22948b7e6d39d9b349bb2a44fa3649e6',
 'Stu_22d3c32655dc405a88b51c967353b667',
 'Stu_23e91cc6c0fb466b738a738f5644ecce',
 'Stu_24010745fb7564616ece8d79e2afc446',
 'Stu_240fa1d98ec791e1d67dc1efb0a40f95',
 'Stu_2437edd414edefba1933409831b041cc',
 'Stu_2449d34687ab0f0439220492d0e0ac72',
 'Stu_245f1e71f4303282c38e923cea850fe0',
 'Stu_2469725f35ef8fb4b03d72ba703c1efc',
 'Stu_2473aef938112af2f237fbbfd8d83ec3',
 'Stu_2489e8834272a15eddea07f551376b87',
 'Stu_249f13b1f823dad06c9bb837edabb426',
 'Stu_24dcae1e103df29b36d9c7ee85ce0bdd',
 'Stu_24e4ff0862c20bda44cb81f92a64acf3',
 'Stu_254def6a2de49a5efea3f4a1f64c5781',
 'Stu_2591ca75792647150e49320a08387c9b',
 'Stu_25ad7d218f85a6cd82018a1c09aeb975',
 'Stu_2611e2e8f9a3c20a4288d7751088fed7',
 'Stu_267e8126aab66d1b7c00813746a33fe0',
 'Stu_26a694cc2f324849f65ddc09c020d9a9',
 'Stu_26f87586c89b7b92e4f8df11996ae711',
 'Stu_27165d72e9bc051c35b6d01616730279',
 'Stu_2739c222849742bc52a495c592f237b7',
 'Stu_27988cf3f6f6241d72d363f9bda9d216',
 'Stu_283109ae51a6c31850d7a749ed96bf9a',
 'Stu_2875c8dc122456818b322af069840956',
 'Stu_287ff9b7460499623f5426b83cb36ddf',
 'Stu_2893d4c82c9c5ab6a4830233d3e0426e',
 'Stu_28a98dd890b34d0e9e81ccb0b0814f14',
 'Stu_2912cafae182c6a369c249378da61757',
 'Stu_292e0e57029ce3a363581c9ead4c3668',
 'Stu_2987371002fe32e24701d2b1cd5e23b8',
 'Stu_29adeff6d581ee266a40c37ccd922fc7',
 'Stu_29e9ac6bbd3b1f57f583bec5a63ed363',
 'Stu_2a53d4b6228eaf691a7c575b7c25f8cf',
 'Stu_2a6531c97809f4a6f894b1a68a178c6a',
 'Stu_2aa2e4a9b6334594fddfa48a24e8ac85',
 'Stu_2ad4de904424ecd61b78bae5213ad4de',
 'Stu_2bfd2b175b8cee53ce1548187e0227b8',
 'Stu_2c396ed479875152888b928c14ceba71',
 'Stu_2c5beef3e571c97b7a0fbb6f5c0267f8',
 'Stu_2c79562d9b7c596272770666a0132285',
 'Stu_2ceb3888c64d7a6abc618943de7c6833',
 'Stu_2cf4f661321b66aecbbac9b210d0b3c7',
 'Stu_2cf5cd418025a81570e5c0fc54986ce2',
 'Stu_2d121fd12b2f25486b336a5636d1f63a',
 'Stu_2d1cff4ebd7a41b9c088f4d336bc949b',
 'Stu_2da043023df90abbb65034745044867b',
 'Stu_2dd5febe3f097e2f4294a9ac7b220adc',
 'Stu_2deff37233ba4110d7a6305330710327',
 'Stu_2e11b738451b649deaf415c036508f98',
 'Stu_2ec2e0c872eb781961fc19b1dff3a5cb',
 'Stu_2ef331c18d7bb2db03feaebbdf0ea1bf',
 'Stu_2efd3ad909d6476ac026d33ff2a3994a',
 'Stu_2ff214cc2a9366bd44ba260e8e9cd35a',
 'Stu_3090954e7794d01ffd4011b39f21d455',
 'Stu_30c26ac35fa8f89f418a4166730e5bad',
 'Stu_30d89dd757c9915cfe3b20d740737a8d',
 'Stu_316402412c052d18dc2018bc78008cb7',
 'Stu_31b23403022f7b08a5aead42c4ce30ca',
 'Stu_3256474c7146179729d2f0fb48302a1e',
 'Stu_3259a55f724281d82fde26584921d923',
 'Stu_3279b45da029af6fe0f386758a19b7ec',
 'Stu_332c69ce89354f0f5d30f38af8216b91',
 'Stu_333be5f7d5695e28ca3b2b55a670ea26',
 'Stu_3351b4a0960b1a8fffc14b28a4e4d35e',
 'Stu_335698cc8ac62756e7e7e6c6c5336151',
 'Stu_33d570a5c2f8a9cbe119a2d90d7e2f01',
 'Stu_346b752ecc1be48cdc8cdcd1783c0a3e',
 'Stu_34bd5b5e023df6238d90b53ff93c1b13',
 'Stu_34d5177b132907ceef227b7150cc9612',
 'Stu_3510fd11b700c235f5b8e3c582f011c4',
 'Stu_3561d6c872316d247b9ffd8e8c6a7a9e',
 'Stu_35e773d06b3e6636e03fff3faedce4d9',
 'Stu_3630025d236ad0789fbe398308e5c2a7',
 'Stu_3676b23b07e3e72910e089edca5c31ad',
 'Stu_3679818d275efa98d8516212eb3da4c4',
 'Stu_36d482753e9d2e79fa7bb3fe8df607fa',
 'Stu_36e2aa2f7142c5b32aed2a1f53daddf8',
 'Stu_374bf798de0eb9920453c3b2413fc627',
 'Stu_37db83911d6fe0e7ad9f3de335876ed1',
 'Stu_3854681adfcb9297096dd7e0ab9fb469',
 'Stu_38d007b26e4564bd1b6ea13450f7e439',
 'Stu_38d9322ba9929ae11f49d22655051651',
 'Stu_394eb2e000edbcb1ea7b22b67f57ae71',
 'Stu_397ed27e7f55d921bb1ccaff96f7f8d5',
 'Stu_39955837abc33809414a614da09e69e7',
 'Stu_39ba153abbca65552b095231e50e96a4',
 'Stu_39d09365f20e77e4473caa039191bf5a',
 'Stu_39f5503c2494e72276c30c668907b70a',
 'Stu_3a11fff284a367683252a84c2a728621',
 'Stu_3a841299d0136875b91bb62bdc22302d',
 'Stu_3aa184c1833b4798d21af7a09cd9fc23',
 'Stu_3ad0b8b73cec0036284fc02133ec2381',
 'Stu_3aeb5c8680a717272097dc51391be862',
 'Stu_3b2074020afda81eafa15c0994d6cfa5',
 'Stu_3bf6feb0f9859ab9706ca2f3d41b3315',
 'Stu_3c2f28c8ac6124e52c70c066c343b75f',
 'Stu_3d07ad4cd1fd99822fb691c7d5c6535e',
 'Stu_3d0cb7976d562b10a78606a4b3a1183b',
 'Stu_3d41ccdd4a4bd03b8e06bdc20e35235a',
 'Stu_3d4dc96909859ddd3a833eec65028115',
 'Stu_3d698454eb2be8221c2e1997ecef9f4c',
 'Stu_3d6d3a9d2dcbcfb3f01c833710c1ecad',
 'Stu_3df35d614436991d9dbed52547e56d57',
 'Stu_3e4de780e3988549f20667df4ffc2eb3',
 'Stu_3e562178a12dc0289ff1eb57bccc4be9',
 'Stu_3e74c4851d95fff61b80d5c96386a172',
 'Stu_3e9036245c4f206603fe3fd07c9386ca',
 'Stu_3ebab4eb5f227ba6779b2d1d1a38150c',
 'Stu_3f851f715b7245df3242a82f8e071f8f',
 'Stu_3f8ed1e4fefb07365232dbc3ecf369cf',
 'Stu_407f30dafc049d8bd1bf830013a0f376',
 'Stu_4154019d0e174e7047d8ffe7f693fa5f',
 'Stu_417755dfcfb36372e431358b99ecc175',
 'Stu_41cbbe220dcb3cecf2dc72db42c76eb0',
 'Stu_41d99e68e9478df55e9992cbce00edaa',
 'Stu_4200ea7a1695730a565d32474adb46fa',
 'Stu_42bbf778613e8d8962876f080ea7b72e',
 'Stu_42c758dcd136eb4382c976e9e27ff10f',
 'Stu_42d44075e2f82cbbae03b90cdbc75201',
 'Stu_42f8139138a16485cfdf787c6f776797',
 'Stu_43184db9c6a3963cc351b697bc21a521',
 'Stu_4351a91b3c5eeba46c1c797706cb48c5',
 'Stu_436dbf4440b53440d1b733451bbc2884',
 'Stu_43acbd28326d258127edc7c661766e3c',
 'Stu_44676891d49fb826980f88c9a50334f8',
 'Stu_446eb3b5aeaf924358730ea5c976d502',
 'Stu_446f012e1e120c4af205d58728759e87',
 'Stu_44913224cd9d0beed72eb525c22de90e',
 'Stu_453608907ab8908e367d7fc7ccfd0da2',
 'Stu_4550adfa685fa8cb6e74fcbcae23f48d',
 'Stu_458e7d38e9f3838f8eb835073c69fc65',
 'Stu_45dac5ea1d03a00d09119730d477cc15',
 'Stu_4660809c9976a2b25dfe0e13987ebe07',
 'Stu_4696c7a285363bc34e6579fb162f9fc1',
 'Stu_47f95f8ecd4bde7a46b8e4a8c69cce54',
 'Stu_480badef8a98b935f2813e832abf696d',
 'Stu_481510f7bdbaca2aeae06814c8b9c0dd',
 'Stu_485762f63572e810c93f24a224c38088',
 'Stu_4857adb150461c2fcb6f54c2b973fbd0',
 'Stu_48a814b4de67bc5b08f1809fcbfe56aa',
 'Stu_4936a73361873458d3e428ff0931aa1e',
 'Stu_496532c6b4dec679bb17fc1cbb746226',
 'Stu_49d91a04c5ff2dddf405035fbd744626',
 'Stu_4a1ea27f84a639cab3ab086d86712c8f',
 'Stu_4a79e66dac87c69aa57bbc5fedde9856',
 'Stu_4ab4a02d587b3cd4aee502e78c1c1383',
 'Stu_4b0edf64921c9f740bfb7aabc3be1c38',
 'Stu_4b1a8fdb778f63e3903c4c6a55d8696e',
 'Stu_4ceeb95731478dd5b0bec616dc59726d',
 'Stu_4cfd4ea579bbfbf2bc646ff59a94d2ac',
 'Stu_4de217a6fdbc0dce99373f23805b8444',
 'Stu_4e0e3d027cc01036de18a667150697b6',
 'Stu_4e3aa4ce194acf91af595a9b85bdafc7',
 'Stu_4e52b4c7f45d9f5c137ccfc6ecad0ebb',
 'Stu_4e9d1ef3ff073dc876e358d755bcf0bd',
 'Stu_4ec408802468858f47358ca7ad93d3f5',
 'Stu_4f430c0a6442a778b066adb401c1f6dd',
 'Stu_4f865148f4349bed83bf4e4d107f76c2',
 'Stu_50a803e1ca105558bf1f1c0d66b6f206',
 'Stu_50c6ce84f4e6b549f6d866714eaa7720',
 'Stu_5152e5a8b7b6c773ffc029ddad30fa82',
 'Stu_51841b7f1def895a55466c4a4852f350',
 'Stu_51ab769ed6840330dcf34bad260eebbb',
 'Stu_51ace53dfda8d308a8f6a1db5978cf8b',
 'Stu_51f2b0d9665474d0f7c21c81cdf43215',
 'Stu_5245c048513b81c229901207c0ca9b92',
 'Stu_526ce9ce924e591a5d5cf50f44ba604d',
 'Stu_5286d083bcec44e21c72eb9d86e90394',
 'Stu_52a3f177ab2b36de44a7b1deacc89c04',
 'Stu_53073a303cfaf212ec79096b614e9983',
 'Stu_5322869c0d66c492fc5efad7dd317921',
 'Stu_537544acad1f35313e91b85673d62fd0',
 'Stu_540a8beed3b125bf1c275c6823441338',
 'Stu_547090ce761571a2d43da8209f298b55',
 'Stu_549e001f7faf54820d9f1be9a92e614d',
 'Stu_54a88a6466c2869ad02e5b97584c1d41',
 'Stu_54eb4691d8666c0f7ee14983baa8d5db',
 'Stu_552ca628202dc5b46bc974456bf9d2ee',
 'Stu_557dcfe2ae14aa416543e8c33bfb2646',
 'Stu_55b8d2aa1216c8bccadcd8b0cf7509fc',
 'Stu_55ce5f2f9200abebec42ebb9c7f72995',
 'Stu_56e1477f7dabb0e73bb38f7bc8d643e2',
 'Stu_576a40f1acc420e456726205745f2893',
 'Stu_57ae7c5055ab8938bb54dc713545d0b8',
 'Stu_57e41bca752ec51eb112687c32c23766',
 'Stu_581fe8d37bd0ecb2e85ce9852d7e85dc',
 'Stu_587c93174fc148a723674648db014149',
 'Stu_587d1380c97fb8ac5463e15da72e0541',
 'Stu_58cb016483574aa13e909dc7de6c2f1e',
 'Stu_58d471ebf98044c718d5252dace3f38f',
 'Stu_58f98bb5080852d14c3f475134d5354b',
 'Stu_590299bf76d867cf5f6a79c4328bc06b',
 'Stu_592ae5a1e825533145462a9dd2b6294a',
 'Stu_59365c63c3c8aab70bcab0a4fc15f62d',
 'Stu_594fe46d0abd9ca196e9dba82796ba4f',
 'Stu_59f8691e8c1564331482913214497585',
 'Stu_5a1992594dbd31569cc53cff2bd4544b',
 'Stu_5a5327edb6d158c7f0a8fe3ac799e48a',
 'Stu_5a91161700b04efdc18a5f74f29122a9',
 'Stu_5a9ac0df921cd102d6951d62a54bb451',
 'Stu_5b3b46f748772c61c0469442403ef997',
 'Stu_5b402e72ab00ad917aed847952fccaa9',
 'Stu_5b974bceaa0cda17c48d20acfe3b1de7',
 'Stu_5beb99cd5a867dfa33c389acdc7fafcf',
 'Stu_5bf8a202b3465db7941060f1996fbc0b',
 'Stu_5c653f72a73109ca2c7aba6aace895b1',
 'Stu_5c66759827fa25bb511c9b4ad403111b',
 'Stu_5c78dc97f08ee152a06036fea2cba9c3',
 'Stu_5cb33f844888faca67d76820a47d947f',
 'Stu_5cc91891160d7c4365c9fe0bc8e8f789',
 'Stu_5ce345c707755761a69c27340bee785b',
 'Stu_5dc346160b9c14c655dd3f259a73fc17',
 'Stu_5e3b2d77bca30ddfdebf04cdffc7cf64',
 'Stu_5e5886c9d9e23ce7ac27ae1388de960a',
 'Stu_5e72ac7d332ce2324c9c91aa1e4c419b',
 'Stu_5f5cdf17bc2b1afb71f7dcff78c0f1c1',
 'Stu_5f7422f376352eee0bb8465b0e8249a7',
 'Stu_5fa04a8266d735ac7f31fcd682d94f25',
 'Stu_6049847f974cd0b1d484adbf3f508766',
 'Stu_60a37a8e43ef5f0f0227dafff0d8fffa',
 'Stu_60f0612e3e8800d284afb61c53be89fb',
 'Stu_618214dba87be09c5ebb7b7f694ab57e',
 'Stu_61d69c1c52dd4abab050cc5e002ddc58',
 'Stu_61eef3c20a95923abe04c845b4653ae5',
 'Stu_624a430bf7e11a594552ee0e64dae248',
 'Stu_6292959c97d2c19b9d28381452956654',
 'Stu_62cd3b5c732c3325cded5c4ada2b707e',
 'Stu_6316a3a49e5253d71213c3f1efdc7730',
 'Stu_63a878fd8ae86fc6847f93a3888d5854',
 'Stu_642c7d984ee266bc89f00f6dd5dbf6e1',
 'Stu_64342b4ac9c18e1958d9201adb990b6b',
 'Stu_648ed131104a8c76fc9b51a8fd2123de',
 'Stu_64b752166da7d1948a14e96a6ff884d9',
 'Stu_64d4332f6d19db34c7567d0fb8327ed9',
 'Stu_653089bbc29cd54fb3df7cf21636309d',
 'Stu_65b460bd2e6ca1b321ff1f51fd748b93',
 'Stu_65ba0676e64e89b9620a659ec5db5b83',
 'Stu_664d6e74d525c89460e6866d1b7c2348',
 'Stu_6715091d8ebfd8a96e0faa6288290855',
 'Stu_6728aba73cc565484fb7e6fe717d8ee8',
 'Stu_676ae9a529b29573aa4674a1a3551b68',
 'Stu_679d31f9a18c48fc81108760d713deed',
 'Stu_67a28d65e4d02d9fbda7e641161ae7a9',
 'Stu_67dd284979daa9e57e6c0023b75c08e5',
 'Stu_681195c205f8de7260e43c67fd3ac080',
 'Stu_68130aeca7716d527c19ac1625cc92b2',
 'Stu_687a09f552a9181c496fe968a371ef97',
 'Stu_688ec82619c623b7b64f632a9168ad91',
 'Stu_689a7c4a6624c34f52cb5a78b9acd142',
 'Stu_68b0b0c245cd11baa871cb0cc3bbc63d',
 'Stu_68d7010f211ddd78e3235851c0e30696',
 'Stu_68e1d0c1d7aa08de5950e109b621fd6e',
 'Stu_68f66a6fc81e6f1e212b264b29adfa28',
 'Stu_6916e44f693d64998f300173247a33b9',
 'Stu_69367d3d3656980a5b1a3bd19e6ebfed',
 'Stu_693b2427ee3affcdf81d8cb0920f51d0',
 'Stu_69405badd58ca2f9d36cd847133f69d8',
 'Stu_69662cf689c14b0bbe16129e9a8ed97c',
 'Stu_6a30bb9b61b2e2f4167ec6a0896e1c45',
 'Stu_6b02f534e8af21879b4f12c30134a707',
 'Stu_6b054a75cc3b4e239657a453bab82864',
 'Stu_6be9398c3f6549e3e11daea7c9ae657d',
 'Stu_6c286618bdcf554250c5fa5fe213104a',
 'Stu_6df37ddfc1758efcca7b3c8d0c635fd2',
 'Stu_6e6df87fe5400efd13c1cbbe67b67e1a',
 'Stu_6eb1c72a4a491be8c11c5e0f8d906ada',
 'Stu_6f0cb87be93529e888473cb3509e07cd',
 'Stu_6f10179bb9dbbc92ddb102acc09185c5',
 'Stu_6f3b0fc7881db2d23c99fca18ca06c74',
 'Stu_6f8562f275d2d5b467b23d642a7d3baf',
 'Stu_708cd42c632678761744ee60ebef0a9d',
 'Stu_7094143358e3bf189d26a69f9cf108f4',
 'Stu_71119f12e41e082eacd17945e5b841c2',
 'Stu_713def6378f36ac49322d66aa146a6e4',
 'Stu_715e873ef0dab5992db4bd2476f608e6',
 'Stu_718e52e378148c89f3f97ae7ea874b61',
 'Stu_7208e5286aa67727804d96de3e01aa63',
 'Stu_722075d1255a52c03767deb8a05ab33d',
 'Stu_722cd5a7ff18dff692a4fcc67f179b8b',
 'Stu_723177d2ebd77b429f4bc6de2c61d810',
 'Stu_724b1c8ee7c6739ed4e64f1313aa89d8',
 'Stu_735489d3d8486ccd51662ae1b4230878',
 'Stu_73e130832986a05c93d8bb3926086205',
 'Stu_743804ec1a15bf7a1d322f82be0c2196',
 'Stu_74dd515fc5bb72b0df3b51d03200a9c8',
 'Stu_7507685ef535bedab5067bfb0a9cf74e',
 'Stu_75cebcf4a269aadec3042ad3710cf8da',
 'Stu_763f864b7513fedb1ad17d306b87e53a',
 'Stu_7717b83690cd1d63ffcf4a8ccdb71da8',
 'Stu_775023f058dcb16a1aa3111e18a607f2',
 'Stu_776d7dbea35dd22e3045159420521119',
 'Stu_77ca7d297cf58bb6686b20c49d706e41',
 'Stu_77dd3057a54f85bc0b1ecefa532d4fc8',
 'Stu_7835a9c27046f04e5b5cde452a876709',
 'Stu_7860db4ff1050bb22e1446645ffb4353',
 'Stu_788acd4517ae800c25df7f46137a7324',
 'Stu_78def4fa83ec384d4dd630ba374a8eb0',
 'Stu_79425cfa7a059ab69e0abb0246a73aee',
 'Stu_795a64d068b29e0394a32af2e6124e17',
 'Stu_79733b6f32d3c68839d87004c0fc388e',
 'Stu_798f459588d76674676c0ef4ee9328fb',
 'Stu_79f5f6cd8e01eac651b7a5a7dfa21999',
 'Stu_7a25ac54643c4a3c6670ba8036638a82',
 'Stu_7a75b6b768e29434a36c8b310a64e0df',
 'Stu_7a92c44653fab4bab92c437050e07450',
 'Stu_7b2e259372ded0eea508dcea224abf8c',
 'Stu_7b368489f62781f2adcb1e6ff25763e2',
 'Stu_7b8d68b1294d22fa7aef952097b84b33',
 'Stu_7ba7b93291c21f23f536befa4bba09ef',
 'Stu_7c0bccb3ed9e54b637f25750a93e9760',
 'Stu_7c9c4111739a8b455bb2cebca797ee48',
 'Stu_7cb96d6d2c7ced835eb28023bb02511a',
 'Stu_7ccc936ed6f77e9e10fbf232d37cb22b',
 'Stu_7d94f8445a03e9ab9d531bd882be4259',
 'Stu_7e31489a2afe9d3c1de53e34aa0a0c5f',
 'Stu_7e6a6e85b1bcffcd063b87edb78e5ada',
 'Stu_7efc7cf1c6b41555ee42f21bc25a7921',
 'Stu_7f2a755eca0bd3632522a9e7de5c03b1',
 'Stu_800301b885fe6c78dbfb1a2169f02f99',
 'Stu_800655aef2f785c980e34c0c92abe364',
 'Stu_802f532d86bf7c0adc3eab0e9a2662f3',
 'Stu_80dc150b18c08370b91f72fa750ce4d5',
 'Stu_8111ccbb3e9c3b8645ad12d0647b4f8a',
 'Stu_81358c2fb2232fa314b94166e9fc5e68',
 'Stu_81bb52f36ec7d0674184c7c6d3f7e17e',
 'Stu_81f9fcf60ab5039d8b835fbcf90355ff',
 'Stu_820c792760cc5f1463181b555d89e096',
 'Stu_82408d6ad7676c34bb83dbe4d1e4a285',
 'Stu_828c37afe0851eae256f911f4ca4ea68',
 'Stu_837bf3b7602ffbd98d2d17c5b54f1e71',
 'Stu_837f12be77a75fa26bb3ce0a08f5830b',
 'Stu_83ab646b5bff65581ba7094b1b053db7',
 'Stu_84ae579bf153792c39d621e402d305d0',
 'Stu_84bd2f2e5d965ce561af28f34dfa1d36',
 'Stu_84f7969c38c5b7087cef358797a0c23c',
 'Stu_852fb22ed7965cecb25611b3e702323d',
 'Stu_855b952faf9100122acba5d9a258865a',
 'Stu_859c13f5e8ae18d98ba3a2f78db25e66',
 'Stu_866de3c986d51d3bcfcfce21d906e0c0',
 'Stu_86a012b7fba742bdc0a88befa053723a',
 'Stu_8849f4d03e375d9ac3ed932fc5d66c62',
 'Stu_889f27121f2bb759485103f3e18c9578',
 'Stu_88a64a33b22224b1f33a167ab3b3f24e',
 'Stu_88c66b16ce600ba906a70703e601c1e2',
 'Stu_89763bcdb176fd7a84cd8bd09f61244f',
 'Stu_89aa853c598133fb33c67a84c702c466',
 'Stu_8a1695cabcd4543e3b21c302da636d73',
 'Stu_8a3872cdb9e1077f68fc13cad46f9996',
 'Stu_8a51c8b997ac8764ea37af2b828f805a',
 'Stu_8a576d08e701ddcc3d2dd288ea98019d',
 'Stu_8a9f9638d7dfb5f2073457e0d005bc8f',
 'Stu_8af447cf522f38f079c8614b842cd252',
 'Stu_8b346a818127012ddd19ba7847c4eda5',
 'Stu_8be4a28e7f7b264c52eb64940eba4e61',
 'Stu_8c82dd5fa22ba638c40bc6d336d7eaaa',
 'Stu_8c98d4ca4cbb740080fbd9d3f0422195',
 'Stu_8cf9624c417e06c115999579074b0818',
 'Stu_8d26566501055b1570bbbfec41ceec4e',
 'Stu_8d4a80561b6cb3984c4f23cd476112fb',
 'Stu_8dd2d0a0225e672cc2e2ecf2367527db',
 'Stu_8dd5172f8c8a5c1a535d3967437fd6c2',
 'Stu_8e48ce9ebc4cf4ce37c053300c52678c',
 'Stu_8e4bfbd1416070e8e79be7e641424971',
 'Stu_8e504a315e7841b8cc8e1564ffa8fd31',
 'Stu_8ea632106a7b2c37e9273afca0611ced',
 'Stu_8f40f13ae5bdc80f475f5fff0c9e89ae',
 'Stu_8f507cf58c8f3f63c86bd6d0c9472083',
 'Stu_8f5e7528404715b0405c1db69e1b7060',
 'Stu_8f684641e5f8e6f465342be93c97c785',
 'Stu_8fad4739b83f899ca26c2940819b4b21',
 'Stu_90521df45c1880fc8a11fe3b82a52bd1',

In [18]:
ds92_tx_Data1[ds92_tx_Data1['Anon Student Id'] == 'Stu_001d187b1b375fe98b88696b250177f0']

,Row,Sample Name,Transaction Id,Anon Student Id,Session Id,Time,Time Zone,Duration (sec),Student Response Type,Student Response Subtype,...,KC Category (MCAS5-State_WPI-Simple).2,KC (MCAS5-State_WPI-Simple).3,KC Category (MCAS5-State_WPI-Simple).3,KC (Single-KC),KC Category (Single-KC),KC (Unique-step),KC Category (Unique-step),School,Class,CF (mich)
0,1,Data1,f4e16b8c0864cb38ffbd487d846a09e1,Stu_001d187b1b375fe98b88696b250177f0,647501,2004-11-10 14:36:52,US/Eastern,102,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC758,NaN,0103999,Class_2,NaN
1,2,Data1,e44529ccdaa26422c653ff9c1efec8c6,Stu_001d187b1b375fe98b88696b250177f0,647501,2004-11-10 14:37:38,US/Eastern,46,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC758,NaN,0103999,Class_2,NaN
2,3,Data1,9915b5078ecd2b8fa0b6f246a021db4b,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:38:50,US/Eastern,70,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC790,NaN,0103999,Class_2,NaN
3,4,Data1,7e36958c6d8d08d9b15ff7f133a76da0,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:39:12,US/Eastern,22,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
4,5,Data1,8f1aef4b136c9ed4ce89c75d9a7dda7c,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:39:14,US/Eastern,2,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
5,6,Data1,4b90d7a61c5e00fcdce020d47ed854e5,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:39:16,US/Eastern,2,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
6,7,Data1,7763fdc98cc2a82d3e0323af8c375209,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:39:39,US/Eastern,23,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
7,8,Data1,fbb2388212cc47ba82e46fe9f1aefab2,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:39:52,US/Eastern,13,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
8,9,Data1,0f826810e52d9103d75b44409e90d227,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:40:01,US/Eastern,9,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
9,10,Data1,f1a6f1f467097c77f0f322551b70c088,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:40:55,US/Eastern,54,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
10,11,Data1,5f2a9fec3a203e4934c0bb3a44d4133a,Stu_001d187b1b375fe98b88696b250177f0,648459,2004-11-10 14:41:38,US/Eastern,10,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC790,NaN,0103999,Class_2,NaN
11,12,Data1,00aa4dd1132be4eb3e048032714945f7,Stu_001d187b1b375fe98b88696b250177f0,648848,2004-11-10 14:43:28,US/Eastern,4,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC790,NaN,0103999,Class_2,NaN
12,13,Data1,082906ca655ec27cc4140cce7af65410,Stu_001d187b1b375fe98b88696b250177f0,648848,2004-11-10 14:43:35,US/Eastern,7,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
13,14,Data1,cb7f30b1f3b23d1ce3e2b361b7efbd4b,Stu_001d187b1b375fe98b88696b250177f0,648848,2004-11-10 14:44:03,US/Eastern,28,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
14,15,Data1,df057bf2d1df1865a20f15003cb88f74,Stu_001d187b1b375fe98b88696b250177f0,648848,2004-11-10 14:44:06,US/Eastern,3,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
15,16,Data1,1fccd977baa736ee6c6d50a4a009841b,Stu_001d187b1b375fe98b88696b250177f0,648848,2004-11-10 14:44:07,US/Eastern,1,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
16,17,Data1,0908e20f9ef38ed3245304a078076805,Stu_001d187b1b375fe98b88696b250177f0,648848,2004-11-10 14:45:01,US/Eastern,54,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
17,18,Data1,650e89f773c7ff899fb86d266f01a487,Stu_001d187b1b375fe98b88696b250177f0,648848,2004-11-10 14:45:14,US/Eastern,13,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC135,NaN,0103999,Class_2,NaN
18,19,Data1,f9337d6e51968aca87c27e1ee3023247,Stu_001d187b1b375fe98b88696b250177f0,649206,2004-11-10 14:45:40,US/Eastern,23,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC542,NaN,0103999,Class_2,NaN
19,20,Data1,7ce97021f321bdb1782257b84a285521,Stu_001d187b1b375fe98b88696b250177f0,649206,2004-11-10 14:46:11,US/Eastern,31,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC285,NaN,0103999,Class_2,NaN
20,21,Data1,8b9297678caf7fcf81003a6d23bde225,Stu_001d187b1b375fe98b88696b250177f0,649206,2004-11-10 14:46:22,US/Eastern,11,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC285,NaN,0103999,Class_2,NaN
21,22,Data1,c46c4f21190028c7bfa58175e7c56920,Stu_001d187b1b375fe98b88696b250177f0,649206,2004-11-10 14:46:31,US/Eastern,9,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC331,NaN,0103999,Class_2,NaN
22,23,Data1,60743151fbfd19fdee9c9ffab8edcdb3,Stu_001d187b1b375fe98b88696b250177f0,649206,2004-11-10 14:46:34,US/Eastern,3,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC331,NaN,0103999,Class_2,NaN
23,24,Data1,8acf21adb0c9c27210d931d400e4cc42,Stu_001d187b1b375fe98b88696b250177f0,649206,2004-11-10 14:46:38,US/Eastern,4,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC463,NaN,0103999,Class_2,NaN
24,25,Data1,cebc13fd0bcab008b8fba92a4cd90994,Stu_001d187b1b375fe98b88696b250177f0,649206,2004-11-10 14:46:56,US/Eastern,18,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC463,NaN,0103999,Class_2,NaN
25,26,Data1,4efb0a5506cf989eea7688fcb97f0080,Stu_001d187b1b375fe98b88696b250177f0,649206,2004-11-10 14:47:45,US/Eastern,49,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC463,NaN,0103999,Class_2,NaN
26,27,Data1,c99637f955bc33bc7fd9449fd38ac94a,Stu_001d187b1b375fe98b88696b250177f0,649206,2004-11-10 14:47:47,US/Eastern,2,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC463,NaN,0103999,Class_2,NaN
27,28,Data1,d596f6c017b7250885fb36b567ae2144,Stu_001d187b1b375fe98b88696b250177f0,649206,2004-11-10 14:48:31,US/Eastern,44,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC463,NaN,0103999,Class_2,NaN
28,29,Data1,93c4a63ceeab251dc08d45deb514e4be,Stu_001d187b1b375fe98b88696b250177f0,649206,2004-11-10 14:48:38,US/Eastern,7,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC119,NaN,0103999,Class_2,NaN
29,30,Data1,94a6eac0fef1e72cfd55da4cb0d02dd4,Stu_001d187b1b375fe98b88696b250177f0,649206,2004-11-10 14:48:39,US/Eastern,1,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC119,NaN,0103999,Class_2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,457,Data1,ba8068c3a56583024106b9de7c1b0851,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 14:59:23,US/Eastern,13,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC208,NaN,0103999,72,NaN
457,458,Data1,115604a4741119a2c18dd17c3412008f,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 14:59:27,US/Eastern,4,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC208,NaN,0103999,72,NaN
458,459,Data1,b8f5353be319b96141b7fe716319b2aa,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 14:59:29,US/Eastern,2,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC208,NaN,0103999,72,NaN
459,460,Data1,2aad4c985f08d946dfcf195e2f3ab2cc,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 14:59:32,US/Eastern,3,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC208,NaN,0103999,72,NaN
460,461,Data1,c95fdf5a07fb85c4f855e7617e39cc74,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 14:59:44,US/Eastern,12,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC208,NaN,0103999,72,NaN
461,462,Data1,d342a1178a867d52da6bd08d4ac5bd41,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 14:59:55,US/Eastern,11,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC764,NaN,0103999,72,NaN
462,463,Data1,d2be167e607e70ecf48a6c30ec438fa2,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 14:59:58,US/Eastern,3,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC764,NaN,0103999,72,NaN
463,464,Data1,f62e3ce97710a89f2a3b0d736f1543f7,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 15:00:13,US/Eastern,15,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC764,NaN,0103999,72,NaN
464,465,Data1,26574097876d71f0fb60a5d6afd780c3,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 15:00:18,US/Eastern,5,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC764,NaN,0103999,72,NaN
465,466,Data1,a75c9623a0316a97f7d6bd8278a58443,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 15:00:27,US/Eastern,9,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC266,NaN,0103999,72,NaN
466,467,Data1,f1e841ca17e972b9dadcc812018346d0,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 15:00:32,US/Eastern,5,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC266,NaN,0103999,72,NaN
467,468,Data1,540c3551e5839abe7239d3b7b7a507b7,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 15:00:35,US/Eastern,3,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC266,NaN,0103999,72,NaN
468,469,Data1,45d491e7e6c7182a7dd8d1bf990b2d23,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 15:00:45,US/Eastern,10,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC266,NaN,0103999,72,NaN
469,470,Data1,a424374e490340bb52bf41f95098c2c1,Stu_001d187b1b375fe98b88696b250177f0,1898788,2005-05-11 15:01:03,US/Eastern,18,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC586,NaN,0103999,72,NaN
470,471,Data1,a082ddfd0a676b269213f10c609b0b97,Stu_001d187b1b375fe98b88696b250177f0,1899396,2005-05-11 15:01:56,US/Eastern,51,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC3,NaN,0103999,72,NaN
471,472,Data1,873a7b814edd4e59015f70bd60a44ecb,Stu_001d187b1b375fe98b88696b250177f0,1899517,2005-05-11 15:02:20,US/Eastern,23,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC215,NaN,0103999,72,NaN
472,473,Data1,12acde8db4c1d9873102a2837998d645,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:02:28,US/Eastern,7,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC130,NaN,0103999,72,NaN
473,474,Data1,2445198c6176b1763a52f53c4d85f378,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:04:52,US/Eastern,144,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC612,NaN,0103999,72,NaN
474,475,Data1,f0063e278b851ab8674fdc557b4229b5,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:04:53,US/Eastern,0.5,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC612,NaN,0103999,72,NaN
475,476,Data1,53984bf456e806de077e61afaef68cc7,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:04:53,US/Eastern,0.5,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC612,NaN,0103999,72,NaN
476,477,Data1,171314e14a968435821e04951bbe2080,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:04:59,US/Eastern,6,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC612,NaN,0103999,72,NaN
477,478,Data1,599fecd1d698984931cb32b1179ee806,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:05:03,US/Eastern,4,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC533,NaN,0103999,72,NaN
478,479,Data1,0a778150d562e5f41e1ae7fb6b3fe995,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:05:04,US/Eastern,1,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC533,NaN,0103999,72,NaN
479,480,Data1,66df7246224f3176b8f62d159ef4dae0,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:05:05,US/Eastern,1,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC533,NaN,0103999,72,NaN
480,481,Data1,38354d1d50fdce2bdca023e5a5d9a52e,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:05:12,US/Eastern,7,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC533,NaN,0103999,72,NaN
481,482,Data1,4382e5dbf9e4911cdbb882bea61fb53f,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:05:25,US/Eastern,13,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC462,NaN,0103999,72,NaN
482,483,Data1,a4d3b7a46dca2b024c1287021db92051,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:05:26,US/Eastern,1,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC462,NaN,0103999,72,NaN
483,484,Data1,8ce876ca235631c385ac0f029894d3b0,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:05:27,US/Eastern,1,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC462,NaN,0103999,72,NaN
484,485,Data1,93c69654e6b3c6b3a71d1ab6536ccef5,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:05:32,US/Eastern,5,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC462,NaN,0103999,72,NaN
485,486,Data1,aaa994d4ed4bc172eaf551fb22861e78,Stu_001d187b1b375fe98b88696b250177f0,1899571,2005-05-11 15:05:38,US/Eastern,6,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC144,NaN,0103999,72,NaN

In [19]:
ds92_tx_Data1.columns

Index(['Row', 'Sample Name', 'Transaction Id', 'Anon Student Id', 'Session Id',
       'Time', 'Time Zone', 'Duration (sec)', 'Student Response Type',
       'Student Response Subtype', 'Tutor Response Type',
       'Tutor Response Subtype', 'Level (Curriculum)', 'Problem Name',
       'Problem View', 'Problem Start Time', 'Step Name', 'Attempt At Step',
       'Is Last Attempt', 'Outcome', 'Selection', 'Action', 'Input',
       'Feedback Text', 'Feedback Classification', 'Help Level',
       'Total Num Hints', 'KC (skills_from_dataframe)',
       'KC Category (skills_from_dataframe)', 'KC (skills_from_dataframe).1',
       'KC Category (skills_from_dataframe).1', 'KC (skills_from_dataframe).2',
       'KC Category (skills_from_dataframe).2', 'KC (skills_from_dataframe).3',
       'KC Category (skills_from_dataframe).3', 'KC (WPI-Apr-2005)',
       'KC Category (WPI-Apr-2005)', 'KC (WPI-Apr-2005).1',
       'KC Category (WPI-Apr-2005).1', 'KC (WPI-Apr-2005).2',
       'KC Category (WPI-Apr-2005).2', 'KC (WPI-Apr-2005).3',
       'KC Category (WPI-Apr-2005).3', 'KC (MCAS39-State_WPI-Simple)',
       'KC Category (MCAS39-State_WPI-Simple)',
       'KC (MCAS39-State_WPI-Simple).1',
       'KC Category (MCAS39-State_WPI-Simple).1',
       'KC (MCAS39-State_WPI-Simple).2',
       'KC Category (MCAS39-State_WPI-Simple).2',
       'KC (MCAS39-State_WPI-Simple).3',
       'KC Category (MCAS39-State_WPI-Simple).3',
       'KC (MCAS5-State_WPI-Simple)', 'KC Category (MCAS5-State_WPI-Simple)',
       'KC (MCAS5-State_WPI-Simple).1',
       'KC Category (MCAS5-State_WPI-Simple).1',
       'KC (MCAS5-State_WPI-Simple).2',
       'KC Category (MCAS5-State_WPI-Simple).2',
       'KC (MCAS5-State_WPI-Simple).3',
       'KC Category (MCAS5-State_WPI-Simple).3', 'KC (Single-KC)',
       'KC Category (Single-KC)', 'KC (Unique-step)',
       'KC Category (Unique-step)', 'School', 'Class', 'CF (mich)'],
      dtype='object')

In [20]:
sample_outcome = ds92_tx_Data1[ds92_tx_Data1['Anon Student Id'] == 'Stu_001d187b1b375fe98b88696b250177f0']['Outcome'].astype(str)
len(sample_outcome)

486

In [21]:
len(sample_outcome[sample_outcome == 'CORRECT'])

143

In [22]:
sample_data = ds92_tx_Data1[ds92_tx_Data1['Anon Student Id'] == 'Stu_001d187b1b375fe98b88696b250177f0']
sample_data.head()

,Row,Sample Name,Transaction Id,Anon Student Id,Session Id,Time,Time Zone,Duration (sec),Student Response Type,Student Response Subtype,...,KC Category (MCAS5-State_WPI-Simple).2,KC (MCAS5-State_WPI-Simple).3,KC Category (MCAS5-State_WPI-Simple).3,KC (Single-KC),KC Category (Single-KC),KC (Unique-step),KC Category (Unique-step),School,Class,CF (mich)
0,1,Data1,f4e16b8c0864cb38ffbd487d846a09e1,Stu_001d187b1b375fe98b88696b250177f0,647501,2004-11-10 14:36:52,US/Eastern,102,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC758,NaN,0103999,Class_2,NaN
1,2,Data1,e44529ccdaa26422c653ff9c1efec8c6,Stu_001d187b1b375fe98b88696b250177f0,647501,2004-11-10 14:37:38,US/Eastern,46,ATTEMPT,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC758,NaN,0103999,Class_2,NaN
2,3,Data1,9915b5078ecd2b8fa0b6f246a021db4b,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:38:50,US/Eastern,70,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC790,NaN,0103999,Class_2,NaN
3,4,Data1,7e36958c6d8d08d9b15ff7f133a76da0,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:39:12,US/Eastern,22,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN
4,5,Data1,8f1aef4b136c9ed4ce89c75d9a7dda7c,Stu_001d187b1b375fe98b88696b250177f0,647792,2004-11-10 14:39:14,US/Eastern,2,HINT_REQUEST,NaN,...,NaN,NaN,NaN,Single-KC,NaN,KC37,NaN,0103999,Class_2,NaN

In [23]:
#print(sample_data.columns)
sample_data[['Duration (sec)', 'Student Response Type', 'Level (Curriculum)', 'Outcome']].head(20)

   Duration (sec) Student Response Type Level (Curriculum)    Outcome
0             102          HINT_REQUEST         Assistment       HINT
1              46               ATTEMPT         Assistment    CORRECT
2              70          HINT_REQUEST         Assistment       HINT
3              22          HINT_REQUEST         Assistment       HINT
4               2          HINT_REQUEST         Assistment       HINT
5               2          HINT_REQUEST         Assistment       HINT
6              23          HINT_REQUEST         Assistment       HINT
7              13               ATTEMPT         Assistment  INCORRECT
8               9               ATTEMPT         Assistment  INCORRECT
9              54               ATTEMPT         Assistment  INCORRECT
10             10               ATTEMPT         Assistment  INCORRECT
11              4               ATTEMPT         Assistment  INCORRECT
12              7               ATTEMPT         Assistment  INCORRECT
13             28               ATTEMPT         Assistment  INCORRECT
14              3          HINT_REQUEST         Assistment       HINT
15              1          HINT_REQUEST         Assistment       HINT
16             54               ATTEMPT         Assistment    CORRECT
17             13               ATTEMPT         Assistment    CORRECT
18             23               ATTEMPT         Assistment  INCORRECT
19             31          HINT_REQUEST         Assistment       HINT